name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore -maxCpuCount

      - name: Test
        run: dotnet test -c Release --no-build

      - name: RunSample
        run: dotnet run --project src/FSharp.Analyzers.Cli/FSharp.Analyzers.Cli.fsproj -- --project ./samples/OptionAnalyzer/OptionAnalyzer.fsproj --analyzers-path ./samples/OptionAnalyzer/bin/Release --verbose
