name: Release

on:
  push:
    branches: [ main ]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  nuget-pack:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/main' }}
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Build
        run: dotnet fsi build.fsx
      - name: Pack
        run: dotnet pack src/FSharp.Analyzers/FSharp.Analyzers.fsproj --configuration Release --output artifacts
      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: artifacts/G-Research.FSharp.Analyzers.*.nupkg
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
            path: ./output

  nuget-publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork && github.ref == 'refs/heads/main' }}
    needs: [ nuget-pack ]
    environment: release
    steps:
      - name: Download NuGet artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
      - name: Publish to NuGet
        run: dotnet nuget push "G-Research.FSharp.Analyzers.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  deploy:
      runs-on: ubuntu-latest
      needs: [ nuget-pack ]
      steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
